### ISSUE TITLE
(Binance) Unable to get symbols

### ISSUE THREAD

**Issue by ujai** [3cqs-coder/SymBot#10]
Error:
Unable to get symbols: {"name":"ExchangeNotAvailable"} binance GET https://api.binance.com/api/v3/exchangeInfo 451 { "code": 0, "msg": "Service unavailable from a restricted location according to 'b. Eligibility' in https://www.binance.com/en/terms. Please contact customer service if you believe you received this message in error." }

**Comment by 3cqs-coder** [comment]
Some exchanges restrict regions that can access their APIs. Binance does this quite often so if your IP address is coming from a location they are restricting this is a typical error they will send. You will need to either contact them or use a server location that Binance allows access from.

**Comment by ujai** [comment]
Indeed, changed region does helps.. thanks!
