### ISSUE TITLE
DCA bot minimum order value 

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#13]
What's the minimum order value of the initial dca order. My findings are low so I'm searching for lowest possible minimum order dca bot so that I can spread them evenly in more than 50 coins

Can I set it to $1 or below like $0.5 or $0.3?

**Comment by 3cqs-coder** [comment]
The minimum order size depends on the exchange and the pair you're trading. Some exchanges will let you trade under $1 and is usually listed on the exchange web site. Here are links to Binance and Coinbase Pro:

https://www.binance.com/en/trade-rule
https://pro.coinbase.com/markets

In a future update, SymBot can retrieve this information automatically if the exchange's APIs provide it.

**Comment by REFLEXGAMING007** [comment]
Can you please recommend me some exchanges that let me trade $1 or less

**Comment by 3cqs-coder** [comment]
Kucoin and OKX have been known to have pairs that can trade under $1.

**Comment by REFLEXGAMING007** [comment]
Thnx alot man!
Btw do you have any discord server?

**Comment by 3cqs-coder** [comment]
You're welcome! There is no Discord server currently, but you can register on https://www.3cqs.com to access additional features like the 3CQS Telegram Bot and WebSocket API that can be used with SymBot and be notified of any updates in the future.
