### ISSUE TITLE
Please add decimal in profit section in telegram notification.

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#15]
In telegram it's always showing $0 as profit because I'm using $0.1 as base order so it's not showing the decimal with profit there.

Please show profit amount with atleast 5 decimal places to catch profits like $0.00075

I'm running 200 to 300 coins with 0.1 as base order that's why 😅 ![Screenshot_20231026-211512532.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/d5b4cf5e-a411-4642-9ff4-52c367634901)

**Comment by 3cqs-coder** [comment]
Thanks for sharing. Currently all profits are rounded to the hundredth decimal place, but this will be considered for a future update.

**Comment by 3cqs-coder** [comment]
This is now fixed in commit #cda2e76
