### ISSUE TITLE
How to Fix 
WARNING: SAND_USDT-4HK0I3H-1698323385 exceeds last updated time by 32.98 minutes

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#16]
![Screenshot_20231026-215652863.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/b60acd86-2f77-41ee-8c30-efcc85e8d589)

**Comment by 3cqs-coder** [comment]
You are likely running too many deals and Kucoin is rate-limiting your access. This is not uncommon, so you may want to reduce the number of deals you're running or contact the exchange for higher limits. Take a look at the FAQ https://github.com/3cqs-coder/SymBot#why-are-my-deals-not-updating-or-not-getting-pricing
