### ISSUE TITLE
Need help about Syntax Error in Bot Config file

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#18]
I'm getting syntax error in cmd when I tried to execute the symbot script

This is the error I'm getting 👇

Bot configuration file error: SyntaxError: Unexpected token 's', ."sphrase": symbot@07#"... is not valid JSON

![Screenshot_3322(2).jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/e8d2b702-fac9-4d28-8abe-6187114c956a)

I'm also attaching my bot config file pic in case there's a problem in it (don't worry those APIs are not valid)👇

![Screenshot_3326.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/129be4b4-8cba-47e1-adcd-e735f5813e8f)

**Comment by 3cqs-coder** [comment]
If you are upgrading, please also confirm any new parameters in app.json are added correctly to your existing app.json configuration file. If any are missing or the JSON format is incorrect, SymBot will fail to start.

**Comment by REFLEXGAMING007** [comment]
It's working perfectly in test mode ( when I remove api key, pass phrase & secret from bot config) but it's keeps giving me this error when I added them back

I believe everything is correct in app config because if it didn't, it properly won't have worked in test mode as well. 
Also probably told me in the cmd what's wrong

**Comment by 3cqs-coder** [comment]
You do not have your apiPassphrase enclosed in quotes, which is breaking the JSON. Any string value must be in quotes.

**Comment by REFLEXGAMING007** [comment]
Okay thanks. I didn't know that. I thought all I had to do was replace null with my thing

**Comment by REFLEXGAMING007** [comment]
Also I'm supposed to keep the the sandbox value true even when I'm trading with real Account right?

**Comment by 3cqs-coder** [comment]
When sandBox: true real orders will never be executed on the exchange. Set to false for real trading. Please keep in mind the software is still considered beta and it is highly recommended to only use sandBox: true.

**Comment by REFLEXGAMING007** [comment]
Wait what I'm confused... 

Isn't sandbox true means paper trading?? 
what do you mean by highly recommending it, Do you mean you highly recommend paper trading or something?

**Comment by 3cqs-coder** [comment]
Yes, sandBox: true is basically paper trading, which is recommended.
