### ISSUE TITLE
GALA/USDT not showing in Symbot

### ISSUE THREAD

**Issue by REFLEXGAMING007** [3cqs-coder/SymBot#38]
GALA/USDT pair from KuCoin isn't showing in Symbot for some reason 👇
![Screenshot_20240211-211053449.jpg](https://github.com/3cqs-coder/SymBot/assets/56241882/25cc0eed-79a6-49e5-b349-47502d63293c)

**Comment by 3cqs-coder** [comment]
The pairs come directly from the exchange's API, so if any are not populating, the exchange is not sending them. If the pair isn't being delisted by the exchange, you can try waiting some time (maybe a few hours or a day) to see if it comes through later on.
